### ISSUE TITLE
conda develop .  error

### ISSUE THREAD

**Issue by 1105430565** [SarahwXU/HiSup#21]
Server configuration: linux system, rtx3090.
According to the readme installation environment, execute the conda develop. command and an error message 'ModuleNotFoundError: No module named 'conda_build'' will be reported. But when I try the pip install conda_build command it keeps failing.

**Comment by SarahwXU** [comment]
Frankly, I never encountered this problem. I did some Google search. It seems there are some issues with the conda-related software. By the way, the library seems to be "conda-build" during installation.

**Comment by cherubicXN** [comment]
Hi @1105430565, you can try to use ``conda install conda-build`` as you may use miniconda instead of anaconda.

Best,
Nan

**Comment by 1105430565** [comment]
The problem with conda develop. has been solved, but I have the following problem when running the ‘’make‘’command：
![image](https://github.com/SarahwXU/HiSup/assets/82871602/fbf98a2b-be8a-40f7-aef7-73f2c5c9ad14)

Except that the version of pycocotools is 2.0.7, because version 2.0.4 keeps reporting errors. The versions of other dependent environments are consistent.
