### ISSUE TITLE
colab cell2 dry run not working 

### ISSUE THREAD

**Issue by AndyJado** [SarahwXU/HiSup#23]
## repreoduce

1. open colab links

2. run cell 1, all good

3. run cell 2, error

**Comment by XJKunnn** [comment]
Hi, could you provide more details about the running error?

**Comment by AndyJado** [comment]
```console
!pip install -r requirements.txt # last time someone run is more than a year ago
```

run cell and vomits:

```console
Building wheels for collected packages: pycocotools
  error: subprocess-exited-with-error
  
  × Building wheel for pycocotools (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Building wheel for pycocotools (pyproject.toml) ... error
  ERROR: Failed building wheel for pycocotools
Failed to build pycocotools
ERROR: Could not build wheels for pycocotools, which is required to install pyproject.toml-based projects
```

Also, I tried `Quickstart with the pretrained model`, the experience is quite sock sniffing.

**Comment by XJKunnn** [comment]
The error is caused by the update of Colab.  The `pycocotools` package is now installed by defaultly now in Colab, so there is no need to install it again.

Additionally, the processing speed is limited by the hardware capabilities of Colab. You can try HiSup on your local device for improved performance.

**Comment by AndyJado** [comment]
I apologize for appearing toxic or something, consider me a kid terrified by python environment.🤦
