### ISSUE TITLE
How does offset regression really work?

### ISSUE THREAD

**Issue by mridvankeles** [SarahwXU/HiSup#24]
I couldnt really understand the idea and the importance of the junctions and heatmap,offset regressions in this repo. 

at the encoder.py ;
xint, yint = junctions[:,0].long(), junctions[:,1].long()
off_x = junctions[:,0] - xint.float()-0.5
off_y = junctions[:,1] - yint.float()-0.5

this part doing the offset convertion from junction x and y points i see that. And at the inference phase, we use those offsets to get score for nms postprocess. I couldnt find much more details neither on the paper nor on the internet. 

ill be preciated if anyone helps. thx

**Comment by SarahwXU** [comment]
The separate heatmap and offset ensure the accuracy of junction detection for predicting the junction location on the 1/4 resolution feature map. You may refer to papers like ''Holistically-Attracted Wireframe Parsing'' and ''End-to-End Wireframe Parsing".
