### ISSUE TITLE
Why we need to detect which vertex is convex or concave?

### ISSUE THREAD

**Issue by mridvankeles** [SarahwXU/HiSup#25]
First of all I couldnt fully understand how we are seperating vertecies by looking at their **convex_hull**? how does that works?

and why we need to seperate them? are we gonna threat **convex vertices** and **concave vertices** differently at the inference phase? 

Any idea from those situations?

**Comment by SarahwXU** [comment]
Calculating the convex_hull is implemented as a way to recognize the convex vertices from all of a building's vertices. The convex and concave vertices will be considered as two different classes during the junction heatmap prediction and are processed separately as in https://github.com/SarahwXU/HiSup/blob/45db55433c9ef713dc52b7dd7f7d56e6645202eb/hisup/utils/polygon.py#L26
The separation reduces the ambiguity between nearby building vertices. We did the ablation study about this division of different types of vertices and the results showed improved performance. However, if the pixel coordinates of vertices of building polygons are far apart from each other and easy to identify, it may not need to set two classes.
