### ISSUE TITLE
some questions

### ISSUE THREAD

**Issue by TomerChen** [SarahwXU/HiSup#6]
Hi, Thanks for the well written and interesting paper. I saw in your paper that you did a comparison experiment with poly world, can I ask you some questions about poly world?

**Comment by SarahwXU** [comment]
Hi,
What are the exact questions? By the way, the PolyWorld has its [offical repository](https://github.com/zorzi-s/PolyWorldPretrainedNetwork).

**Comment by TomerChen** [comment]
> 

Can you share the polyworld training code？Thank you very much!

**Comment by TomerChen** [comment]
> Hi, What are the exact questions? By the way, the PolyWorld has its [offical repository](https://github.com/zorzi-s/PolyWorldPretrainedNetwork).

Can you share the polyworld training code？Thank you very much!

**Comment by SarahwXU** [comment]
I am afraid that we can't. We do not have the training code of PolyWorld either. If you read our paper carefully, you will know that we only use the inference code in our experiments.
