### ISSUE TITLE
ModuleNotFoundError: No module named 'hisup.csrc.lib.afm_op.CUDA'

### ISSUE THREAD

**Issue by 995022989** [SarahwXU/HiSup#9]
作者你好！很荣幸能够拜读您的论文，但是当我尝试运行您的训练代码的时候出现了如下的错误，可以帮我一下吗。
![}WPBGOTDQ (WPIEWL57UKN5](https://user-images.githubusercontent.com/83114196/223949870-04f780a7-a6bc-4534-930f-80006a46081e.png)
另外，我的电脑是Windows操作系统，不知道这是否对代码的正确运行是否有影响。
期待您的回复！

**Comment by SarahwXU** [comment]
Hi,
Have you successfully run the "Installation" according to README.md? If not, you may have to rewrite the makefile to compile the code of afm first.

**Comment by 995022989** [comment]
> 
Sorry, I'm a novice. I don't know how to rewrite the makefile file. Can you provide a method to run the model under Windows? Thank you very much if you can.

**Comment by 995022989** [comment]
> Hi, Have you successfully run the "Installation" according to README.md? If not, you may have to rewrite the makefile to compile the code of afm first.

Sorry, I'm a novice. I don't know how to rewrite the makefile file. Can you provide a method to run the model under Windows? Thank you very much if you can.

**Comment by cherubicXN** [comment]
[Windows Subsystem for Linux (WSL)](https://learn.microsoft.com/en-us/windows/ai/directml/gpu-cuda-in-wsl)  would be a great choice to run Linux programs on Windows as it supports CUDA functionalities as long as you correctly setup the environment.

For our training code, we didn't have any plan to adopt it on Windows because we didn't have any Windows GPU server.

**Comment by 654493176** [comment]
> > Hi, Have you successfully run the "Installation" according to README.md? If not, you may have to rewrite the makefile to compile the code of afm first.
> 
> Sorry, I'm a novice. I don't know how to rewrite the makefile file. Can you provide a method to run the model under Windows? Thank you very much if you can.

你直接手动运行一下makefile里面的命令就行了 windows也能编译的（我是vs2019）

**Comment by 995022989** [comment]
> > > Hi, Have you successfully run the "Installation" according to README.md? If not, you may have to rewrite the makefile to compile the code of afm first.
> > 
> > 
> > Sorry, I'm a novice. I don't know how to rewrite the makefile file. Can you provide a method to run the model under Windows? Thank you very much if you can.
> 
> 你直接手动运行一下makefile里面的命令就行了 windows也能编译的（我是vs2019）

请问这个项目你在Windows系统下成功运行起来了吗，我按照你的办法安装了vs2019后重新运行了makefile里面的命令，但是出现了如下错误，如果你能帮助我将感激不尽。
![38XOD8YZ5)69Y2C$RDB6C_3](https://user-images.githubusercontent.com/83114196/224476961-dfa5fe0c-63d3-4080-bc1d-3f164ea310f4.png)

**Comment by whale-zhu** [comment]
> > > > Hi, Have you successfully run the "Installation" according to README.md? If not, you may have to rewrite the makefile to compile the code of afm first.
> > > 
> > > 
> > > Sorry, I'm a novice. I don't know how to rewrite the makefile file. Can you provide a method to run the model under Windows? Thank you very much if you can.
> > 
> > 
> > 你直接手动运行一下makefile里面的命令就行了 windows也能编译的（我是vs2019）
> 
> 请问这个项目你在Windows系统下成功运行起来了吗，我按照你的办法安装了vs2019后重新运行了makefile里面的命令，但是出现了如下错误，如果你能帮助我将感激不尽。 ![38XOD8YZ5)69Y2C$RDB6C_3](https://user-images.githubusercontent.com/83114196/224476961-dfa5fe0c-63d3-4080-bc1d-3f164ea310f4.png)
> 
> 2023/3/12该问题解决了。

您好！我也遇到了同样的问题，windows10系统，vs2019，但是问题没有解决，期待您的回复。
